### ISSUE TITLE
Perhaps join forces with the VulkanOnD3D12 project?

### ISSUE THREAD

**Issue by volkertb** [msiglreith/rostkatze#1]
Hi,

First of all, kudos on working on this initiative. It seems quit useful.

However, there is already another project on GitHub, which I believed has the same goal:

https://github.com/Chabloom/VulkanOnD3D12

Wouldn't it be advisable for you to join forces with @mdcasey and merge these two projects?

Thank you kindly for considering this.

**Comment by oscarbg** [comment]
Seems they (want to) support UWP with custom surface extension similar to MoltenVK has IOS and MacOS surf.extensions..
Do you plan bring UWP support also?
Please also take a look at all (hope great) requests I made which also apply here. can open a separate issue here if you want .. https://github.com/Chabloom/VulkanOnD3D12/issues

**Comment by msiglreith** [comment]
Hello!
@volkertb I skimmed over their implementation and rostkatze seems to be more feature complete as far as I can see.
@oscarbg UWP support should be relatively easy to achieve (new surface extension and swapchain creation handling). I haven't looked into providing project custom extensions so far, focus currently lays on implementing core features. I'm also happy about contributions for new extensions/features :)

* depth bounds: already implemented
* multigpu: difficult to test and vulkan extension is not stable iirc
* wave/lane ops: mostly depending on SPIRV-Cross support
* multview and hdr: no experience with this, also difficult to test without hardware
* sample locations: probably, just no focus on it

**Comment by oscarbg** [comment]
Thanks for you info!
Just two things to say multiview strictly speaking doesn’t need hardware to implement/test AFAIK.. it’s  a “what eye” value in shader from implementations view.. anyway real usage is VR..  
HDR well.. at least Microsoft has minimal D3D12 HDR sample.. that requests in DXGI 8 or 10 bit backbuffer.. well might help you here, I have the hardware, if you copy paste Microsoft code can check all is working.. or might test by myself, let’s see..
@msiglreith first I forgot thanks for your effort seems a very nice project.. hope doesn't stagnate and keeps evolving for a long time..
seeing you are fast to answer :-) let me ask a few more I forgot:
1) I asked sample locations because I saw **Chabloom seems to support conservative raster. already**.. they merged from a (very small ) pull request so perhaps no much work to merge in your project..
2) tiled resources/sparse textures.. could be useful in AMD case.. I see on vulkan.gpuinfo many caps related to sparse resources not supported on Vega although Vega GPU D3D12 drv. support Maximum tier 3 (volume tiled Tex.) I have Vega also to test..
3) all number types:
 do you support float64 double precision?, also what about int64 and int16 Vulkan optional cap. (this will require feeding SM6.x to DX12 so compiling to DXIL instead of DXBC( I mean can’t use d3dcompiler APIs or FXC) I imagine similar to wave ops case perhaps is more a Spirv-cross issue....
If yes maybe it’s time to do requests referencing this project as use case..
I left as final case the more interesting to me float16 this doesn’t need DXIL can be achieved via DXBC 
using HLSL min16float..
I’m interested in this case for example for Intel iGPUs don’t support Vulkan float16 cap (I mean on SPIRV generated code ) but support min16float at almost 2x speed up tested on mandebrot shader..
Can send you sample Vulkan compute shader mandelbrot program supporting float16 float32 and 64 if you want to implement complete integer and fp support..
4) well I forgot.. I will edit later..
EDIT:
4) Ok was really about implementing dxcompiler support for DXIL support with all number types/widths and things like wave ops..
what I mean here is you support in addion to d3dcompiler new library for sm6.x DXIL (**dxcompiler.dll**)
please take a look here on usage: https://blogs.msdn.microsoft.com/marcelolr/2017/03/27/directx-compiler-apis/
all in all as you say SPIRV-cross may be more blocking using new DXIL "new things"..
5) raster oder views (well not supported right now on Vulkan but seeing GDC is around the corner and a many new extensions hope get announced I think raster order views ext. will be published this month)
so just asking to consideration for when vulkan supports it..

one comment I see you support ExecuteIndirect:

are you using NVX_device_generated_commands.. remember seeing time ago that executeindirect model was not fully supported by Vulkan and that NV ext. supported what was lacking in Vulkan and even exposed more powerful paradigm.. just asking maybe I'm wrong..

**Comment by msiglreith** [comment]
2. AFAIK sparse resource uploads are sync due to WDDM, which renders them quite useless (information might be outdated)
3. I'm happy about samples for testing, types probably depending on SPIRV-Cross support.
5. Possible but difficult as users need to be aware of shader resource interface translation and general internals of SPIRV-Cross and rostkatze, making it more difficult to write 'correct' HLSL shaders (e.g structured UAV buffers not possible, register space layout, ..)

ExecuteIndirect: Something I already considered as command signatures are more powerful than Vulkan. Other feature I would like to implement in the future would be predication.

**Comment by oscarbg** [comment]
@msiglreith thanks for all info..
first of all, how can be that I forgot to ask one important feature at least for press sites: **async compute**.. do you support it currently i.e. independent compute queues?
of course this is a targeted AMD only optimization right now (well Nvidia supports async compute on Pascal seems even on Vulkan driver)..
some minimal samples to test async compute:
I testing one I will choose to test first example:
https://github.com/jherico/Vulkan/commit/638c4859fc805b84de9c3883fa82c2cf60a56e46
https://github.com/LarsIngo/VulkanProject
https://github.com/Chainsawkitten/AsyncCompute
https://github.com/JoeJGit/Vulkan-Async-Compute-Test
2)didn't know sparse made no much sense on PC due to sync.. for sure must be ok on Xbox X which should run some variant of WDDM as it has a modified Windows.. 
3)give me some time to clean a little the samples and will post here..
4) ok I'm ignorant here and I don't know really the details but IMHO seems at least dxc compiler is a drop in replacament for fxc and works very well so sorry but can't see what new difficulties brings using "new" dxcompiler vs d3dcompiler API.. in fact all difficulties you have overcome already using SPIRV-cross+d3dcompiler should pay off to a spirv-cross+dxcompiler transition..

Interesting to header predication I also forgot totally.
thanks..

**Comment by msiglreith** [comment]
Async compute is no real feature, exposing multiple queues is doable, but UAVs are a bit tricky due to pipeline barriers (see wiki). Another problem is resource sharing across queues.

Regarding the dxil stuff, I assumed you wanted to create shader modules from hlsl/dxbc/dxil instead of spirv. Using the new open llvm compiler would be a possibility but not high priority for now.
The shader compilation pipeline is currently: SPIRV - SPIRV-Cross - D3DCompile - DXBC - Driver
Wave op support is still 'bottlenecked' by SPIRV-Cross except allowing to directly use 'native' shaders, which I'm not really looking forward to (see comment above).
